apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: db-payments
    name: db-payments
spec:
    ports:
        - name: jdbc
          port: 5432
          targetPort: 5432
    selector:
        io.kompose.service: db-payments
